### ISSUE TITLE
Can not specify external display

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_turtle#11]
It looks like the idea was to be able to pass in a `display` object to override the default of using `board.DISPLAY`. However, for boards with no built in display, currently can not even import the library:
```python
Adafruit CircuitPython 5.0.0-alpha.4 on 2019-09-15; Adafruit Circuit Playground Bluefruit with nRF52840
>>> from adafruit_turtle import turtle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/travis/build/adafruit/Adafruit_CircuitPython_Bundle/libraries/helpers/turtle/adafruit_turtle.py", line 136, in <module>
  File "/home/travis/build/adafruit/Adafruit_CircuitPython_Bundle/libraries/helpers/turtle/adafruit_turtle.py", line 139, in turtle
AttributeError: 'module' object has no attribute 'DISPLAY'
>>> 
```

**Comment by caternuson** [comment]
Fixed with #12
